name: build_whl
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: download file
        run: |
          bitsadmin /transfer myDownLoadJob /download /priority normal "https://files.pythonhosted.org/packages/39/5f/fd9384fdcb9cd0388088899c110838007f49f5da1dd1ef6749bfb728a5da/PyQt5_sip-12.11.0.tar.gz" "$HOME/PyQt5_sip-12.11.0.tar.gz" 
      - name: tar zvxf file
        run: |
          tar zvxf $HOME\PyQt5_sip-12.11.0.tar.gz -C $HOME
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install wheel setuptools
      - run: pip wheel --wheel-dir=$HOME $HOME\PyQt5_sip-12.11.0
      - run: ls $HOME
      - uses: actions/upload-artifact@v3
        with:
          name: PyQt5_sip-12.11.0-cp311-cp311-win_amd64.whl
          path: C:\Users\runneradmin\PyQt5_sip-12.11.0-cp311-cp311-win_amd64.whl
