name: build_netbootxyz
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      forceBuild:
        description: "Force image build"
        required: false
        default: false
        type: boolean

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      netbootxyz_release: ${{ steps.netboot.outputs.release }}
      build_image: ${{ steps.check.outputs.build_image }}
    steps:
      - name: Get latest release of netboot.xyz
        id: netboot
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: netbootxyz
          repo: netboot.xyz
          excludes: prerelease, draft
      - name: Check if new Docker image should be built
        id: check
        run: |
          BUILD_IMAGE=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.forceBuild == 'true' }}

          if ! "$BUILD_IMAGE"; then
            docker buildx imagetools inspect xin053/netbootxyz-files:${{ steps.netboot.outputs.release }} > /dev/null || BUILD_IMAGE=true
          fi

          echo "build_image=${BUILD_IMAGE}" >> $GITHUB_OUTPUT

  build:
    name: Build and push
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.build_image == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download netboot latest release files
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "netbootxyz/netboot.xyz"
          tag: ${{ needs.check.outputs.netbootxyz_release }}
          fileName: "*"
          out-file-path: "netbootxyz"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:netbootxyz"
          push: true
          tags: xin053/netbootxyz-files:${{ needs.check.outputs.netbootxyz_release }}
