name: capi-sync-image
on:
  workflow_dispatch:
    inputs:
      dest-registry:
        description: "Destination registry to push image"
        required: true
        default: "harbor-eme.chinamye.com"
        type: string

      dest-project:
        description: "Destination project to push image"
        required: true
        default: "capi"
        type: string

jobs:
  build_manifest_matrix:
    runs-on: ubuntu-latest
    outputs:
      manifest-files: ${{ steps.list-manifests.outputs.manifest-files }}
    steps:
      - name: Checkout capi-helm-charts
        uses: actions/checkout@v4
        with:
          repository: xin053/capi-helm-charts
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: List manifests
        id: list-manifests
        # Use jq to format the manifest list as a JSON array
        run: |
          MANIFEST_FILES="$(ls ./skopeo-manifests/*.yaml | jq -c -s -R 'split("\n") | map(select(length > 0))')"
          echo "manifest-files=$MANIFEST_FILES" >> $GITHUB_OUTPUT

  sync_images:
    runs-on: ubuntu-latest
    needs: [build_manifest_matrix]
    strategy:
      # Restrict the maximum number of parallel syncs to avoid quay.io push limits
      # Anonymous pulls are not rate-limited
      max-parallel: 4
      # If one sync fails, continue with the others
      fail-fast: false
      matrix:
        manifest-file: ${{ fromJSON(needs.build_manifest_matrix.outputs.manifest-files) }}
    steps:
      - name: Checkout capi-helm-charts
        uses: actions/checkout@v4
        with:
          repository: xin053/capi-helm-charts
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # Just sync all the images in all the manifests to GitHub packages
      - name: Sync component images
        run: |-
          podman run \
            -v ./skopeo-manifests:/opt/skopeo-manifests \
            -w /opt \
            quay.io/skopeo/stable:latest \
            sync \
              --src yaml \
              --dest docker \
              --dest-creds "${{ secrets.DEST_REGISTRY_USERNAME }}:${{ secrets.DEST_EME_REGISTRY_PASSWORD }}" \
              --scoped \
              --all \
              ${{ matrix.manifest-file }} \
              ${{ github.event.inputs.dest-registry }}/${{ github.event.inputs.dest-project }}
