name: diskimage-builder-octavia
on:
  workflow_dispatch:
    inputs:
      image-version:
        description: "Which image version to build"
        required: true
        type: choice
        options:
          - 2024.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install packages
        run: |
          sudo apt update && sudo apt install -yq debootstrap qemu-utils git kpartx python3-pip
          sudo pip install diskimage-builder

      - name: Git clone
        uses: actions/checkout@v4
        with:
          repository: openstack/octavia
          path: octavia
          ref: "stable/${{ github.event.inputs.image-version }}"

      - name: Build image
        run: "cd $GITHUB_WORKSPACE/octavia/diskimage-create && sudo bash ./diskimage-create.sh -r Mye2024@Octavia"

      - name: List files
        run: "ls -alh $GITHUB_WORKSPACE/octavia/diskimage-create"

      - name: Rename files
        run: "cd $GITHUB_WORKSPACE/octavia/diskimage-create && for file in *.qcow2 *.raw; do if [ -f $file ]; then if [[ $(stat --printf='%s' $file) -gt 2097152000 ]]; then sudo split --bytes=2000M --numeric-suffixes=1 $file octavia_${{ github.event.inputs.image-version }}_$file.part && sudo rm -f $file; else sudo mv $file octavia_${{ github.event.inputs.image-version }}_$file;fi;fi;done"

      - name: Md5sum
        run: |
          cd $GITHUB_WORKSPACE/octavia/diskimage-create
          echo "md5sum:" >> md5sum.txt
          for file in *.qcow2* *.raw*; do if [ -f $file ]; then md5sum $file >> md5sum.txt;fi;done

      - name: List files again
        run: "ls -alh $GITHUB_WORKSPACE/octavia/diskimage-create"

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: dib_octavia_${{ github.event.inputs.image-version }}_${{ steps.date.outputs.date }}
          tag_name: dib_octavia_${{ github.event.inputs.image-version }}_${{ steps.date.outputs.date }}
          body_path: ${{ github.workspace }}/octavia/diskimage-create/md5sum.txt
          files: |
            ./octavia/diskimage-create/*.qcow2
            ./octavia/diskimage-create/*.qcow2.part*
            ./octavia/diskimage-create/*.raw
            ./octavia/diskimage-create/*.raw.part*
