name: diskimage-builder
on:
  workflow_dispatch:
    inputs:
      build-param:
        description: "Param of build_images.sh"
        required: false
        type: string
      image-description:
        description: "Image description (used to generate release description)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Echo build-param
        run: echo ${{ github.event.inputs.build-param }}
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
        
      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    
      - name: Checkout mye-scripts
        uses: actions/checkout@v4
        with:
          repository: xin053/mye-scripts
          path: mye-scripts
          ref: 'master'
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build image
        run: "cd $GITHUB_WORKSPACE/mye-scripts && sudo GITHUB_ACTION=yes STORE_PATH=$GITHUB_WORKSPACE/mye-scripts ${{ github.event.inputs.build-param }} bash ./build_image.sh"

      - name: List files
        run: "ls -alh $GITHUB_WORKSPACE/mye-scripts"

      - name: Rename files
        run: "cd $GITHUB_WORKSPACE/mye-scripts && for file in *.qcow2 *.raw; do if [[ $(stat --printf='%s' $file) -gt 2147483648 ]]; then sudo split --bytes=2G --numeric-suffixes=1 $file ${{ github.event.inputs.image-description }}_$file.part; else sudo mv $file ${{ github.event.inputs.image-description }}_$file;fi;done"

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: dib_${{ github.event.inputs.image-description }}_${{ steps.date.outputs.date }}
          tag_name: dib_${{ github.event.inputs.image-description }}_${{ steps.date.outputs.date }}
          files: |
            ./mye-scripts/*.qcow2
            ./mye-scripts/*.qcow2.part*
            ./mye-scripts/*.raw
            ./mye-scripts/*.raw.part*
