name: diskimage-builder
on:
  workflow_dispatch:
    inputs:
      image-description:
        description: "Image description (used to generate release description)"
        required: true
        type: string
      image-version:
        description: "Which image version to build"
        required: true
        type: choice
        options:
          - ubuntu-24.04-noble
          - ubuntu-22.04-jammy
          - ubuntu-20.04-focal
          - ubuntu-18.04-bionic
          - ubuntu-16.04-xenial
          - centos-8
          - centos-7
          - debian-12-bookworm
          - debian-11-bullseye
          - debian-10-buster
          - debian-9-stretch
          - fedora-40
          - fedora-39
          - fedora-38
          - fedora-37
          - fedora-36
          - rocky-9
          - rocky-8
      boot-mode:
        description: "Boot mode"
        required: true
        type: choice
        options:
          - bios
          - uefi
      image-format:
        description: "Image format"
        required: true
        type: choice
        options:
          - qcow2
          - raw
      ironic-partition-image:
        description: "Build ironic partition image or not"
        required: false
        type: choice
        options:
          - no
          - yes
      fedora-v2v-image:
        description: "Build fedora v2v image or not"
        required: false
        type: choice
        options:
          - no
          - yes
      nvidia-driver:
        description: "Build image with nvidia-driver"
        required: false
        type: choice
        options:
          - no
          - yes-535
          - yes-550
      build-param:
        description: "Param of build_images.sh"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo build-param
        run: echo ${{ github.event.inputs.build-param }}
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
        
      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
    
      - name: Checkout mye-scripts
        uses: actions/checkout@v4
        with:
          repository: xin053/mye-scripts
          path: mye-scripts
          ref: 'master'
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Get image info
        id: image
        run: |
          IFS='-' read -ra parts <<< ${{ github.event.inputs.image-version }}
          echo "image_type_lower=$(echo ${parts[0]} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "image_type_upper=$(echo ${parts[0]} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
          echo "image_version=${parts[-1]}" >> $GITHUB_OUTPUT
          IFS='-' read -ra parts <<< ${{ github.event.inputs.nvidia-driver }}
          echo "nvidia_driver=${parts[0]}" >> $GITHUB_OUTPUT
          echo "nvidia_driver_version=${parts[1]}" >> $GITHUB_OUTPUT
          if [[ ${parts[0]} == "no" ]]; then
            echo "image_description=${{ github.event.inputs.image-description }}_${{ github.event.inputs.boot-mode }}" >> $GITHUB_OUTPUT
          else
            echo "image_description=${{ github.event.inputs.image-description }}_${{ github.event.inputs.boot-mode }}_nvidia_${parts[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Get build image command
        id: command
        run: |
          echo 'build_image_command="GITHUB_ACTION=yes STORE_PATH=$GITHUB_WORKSPACE/mye-scripts IMAGE=${{ steps.image.outputs.image_type_lower }} ${{ steps.image.outputs.image_type_upper }}_RELEASE=${{ steps.image.outputs.image_version }} BOOT_MODE=${{ github.event.inputs.boot-mode }} IRONIC_PARTITION_IMAGE=${{ github.event.inputs.ironic-partition-image }} FEDORA_V2V=${{ github.event.inputs.fedora-v2v-image }} NVIDIA_DRIVER=${{ steps.image.outputs.nvidia_driver }} NVIDIA_DRIVER_VERSION=${{ steps.image.outputs.nvidia_driver_version }} IMAGE_FORMAT=${{ github.event.inputs.image-format }} ${{ github.event.inputs.build-param }} bash ./build_image.sh"' >> $GITHUB_OUTPUT

      - name: Echo build image command
        run: "echo ${{ steps.command.outputs.build_image_command }}"
      
      - name: Build image
        run: "cd $GITHUB_WORKSPACE/mye-scripts && sudo ${{ steps.command.outputs.build_image_command }}"

      - name: List files
        run: "ls -alh $GITHUB_WORKSPACE/mye-scripts"

      - name: Rename files
        run: "cd $GITHUB_WORKSPACE/mye-scripts && for file in *.qcow2 *.raw *.vmlinuz *.initrd; do if [ -f $file ]; then if [[ $(stat --printf='%s' $file) -gt 2147483648 ]]; then sudo split --bytes=2G --numeric-suffixes=1 $file ${{ steps.image.outputs.image_description }}_$file.part && sudo rm -f $file; else sudo mv $file ${{ steps.image.outputs.image_description }}_$file;fi;fi;done"

      - name: Md5sum
        run: |
          cd $GITHUB_WORKSPACE/mye-scripts
          echo "md5sum:" >> md5sum.txt
          for file in *.qcow2* *.raw* *.vmlinuz* *.initrd*; do if [ -f $file ]; then md5sum $file >> md5sum.txt;fi;done

      - name: List files again
        run: "ls -alh $GITHUB_WORKSPACE/mye-scripts"

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: dib_${{ steps.image.outputs.image_description }}_${{ steps.date.outputs.date }}
          tag_name: dib_${{ steps.image.outputs.image_description }}_${{ steps.date.outputs.date }}
          body_path: ${{ github.workspace }}/mye-scripts/md5sum.txt
          files: |
            ./mye-scripts/*.qcow2
            ./mye-scripts/*.qcow2.part*
            ./mye-scripts/*.raw
            ./mye-scripts/*.raw.part*
            ./mye-scripts/*.vmlinuz
            ./mye-scripts/*.vmlinuz.part*
            ./mye-scripts/*.initrd
            ./mye-scripts/*.initrd.part*
