name: gpu_burn
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Install dependency
        run: |
          sudo apt update && sudo apt install -y build-essential nvidia-cuda-toolkit

      - name: Checkout gpu-burn
        uses: actions/checkout@v4
        with:
          repository: wilicc/gpu-burn
          path: gpu-burn
          ref: 'master'

      - name: Build gpu_burn
        run: |
          cd $GITHUB_WORKSPACE/gpu-burn && sudo make && sudo mv gpu_burn gpu_burn_${{ matrix.os }} && sudo mv compare.ptx compare.ptx_${{ matrix.os }}

      - name: List files
        run: "ls -alh $GITHUB_WORKSPACE/gpu-burn"

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: gpu-burn_${{ steps.date.outputs.date }}
          tag_name: gpu-burn_${{ steps.date.outputs.date }}
          files: |
            ./gpu-burn/gpu_burn_ubuntu*
            ./gpu-burn/compare.ptx_ubuntu*

