name: gpu_burn
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
      
      - name: Install dependency
        run: |
          sudo apt update && sudo apt install -y build-essential nvidia-cuda-toolkit

      - name: Checkout mye-scripts
        uses: actions/checkout@v4
        with:
          repository: wilicc/gpu-burn
          path: gpu-burn
          ref: 'master'

      - name: Build gpu_burn
        run: |
          cd $GITHUB_WORKSPACE/gpu-burn && sudo make

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: gpu-burn_${{ steps.date.outputs.date }}
          tag_name: gpu-burn_${{ steps.date.outputs.date }}
          files: |
            ./mye-scripts/gpu_burn
