name: maas-images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install packages
        run: "sudo apt update && sudo apt install -y qemu-utils qemu-system ovmf cloud-image-utils libnbd-bin nbdkit fuse2fs parted make tree"
    
      - name: Git clone maas-images
        run: "sudo git clone https://git.launchpad.net/maas-images --recurse-submodules"

      - name: Setup maas-images env
        run: "sudo bash $GITHUB_WORKSPACE/maas-images/system-setup"
          
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: Build image
        run: "sudo mkdir -p $GITHUB_WORKSPACE/maas-images/output && sudo $GITHUB_WORKSPACE/maas-images/bin/meph2-import packer-maas.yaml $GITHUB_WORKSPACE/maas-images/output"

      - name: List files
        run: "sudo tree -L 3"
