name: packer-maas
on:
  workflow_dispatch:
    inputs:
      image-type:
        description: "Which image to build (packer-maas directory)"
        required: true
        type: string
      image-version:
        description: "Which image version to build (used for ubuntu,debian,windows)"
        required: true
        type: string
      image-description:
        description: "Image description (used to generate release description)"
        required: true
        type: string
      boot-mode:
        description: "Which boot mode image to build"
        required: false
        type: choice
        options: 
          - uefi
          - bios
      windows-iso:
        description: "windows iso"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
        
      - name: enable KVM for linux runners
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Windows hack
        if: github.event.inputs.image-type == 'windows'
        run: "wget ${{ github.event.inputs.windows-iso }} && ls -alh && exit 1"

      - name: Install packages
        run: "sudo apt update && sudo apt install -y qemu-utils qemu-system ovmf cloud-image-utils libnbd-bin nbdkit fuse2fs parted make tree"

      - name: Install packer
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install packer
    
      - name: Checkout packer-maas
        if: github.event.inputs.image-type != 'windows'
        uses: actions/checkout@v4
        with:
          repository: canonical/packer-maas
          path: packer-maas

      - name: Checkout packer-maas
        if: github.event.inputs.image-type == 'windows'
        uses: actions/checkout@v4
        with:
          repository: canonical/packer-maas
          path: packer-maas
          ref: windows

      - name: Windows hack
        if: github.event.inputs.image-type == 'windows'
        run: "sed -i s#SERVERSTANDARD#SERVERDATACENTER#g $GITHUB_WORKSPACE/packer-maas/windows/Makefile"

      - name: Cache packer image
        uses: actions/cache@v3
        with:
          path: /root/.cache/packer/
          key: ${{ runner.os }}_packer-maas_base-images

      - name: Build image
        run: "cd $GITHUB_WORKSPACE/packer-maas/${{ github.event.inputs.image-type }} && sudo packer init . && sudo SERIES=${{ github.event.inputs.image-version }} VERSION=${{ github.event.inputs.image-version }} BOOT=${{ github.event.inputs.boot-mode }} ISO=${{ github.event.inputs.windows-iso }} make all"

      - name: List files
        run: "ls -alh $GITHUB_WORKSPACE/packer-maas/${{ github.event.inputs.image-type }}"

      - name: Rename files
        run: "cd $GITHUB_WORKSPACE/packer-maas/${{ github.event.inputs.image-type }} && for file in *.gz; do if [[ $(stat --printf='%s' $file) -gt 2147483648 ]]; then sudo split --bytes=2G --numeric-suffixes=1 $file ${{ github.event.inputs.image-description }}_$file.part; else sudo mv $file ${{ github.event.inputs.image-description }}_$file;fi;done"

      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: maas_${{ github.event.inputs.image-description }}_${{ steps.date.outputs.date }}
          tag_name: maas_${{ github.event.inputs.image-description }}_${{ steps.date.outputs.date }}
          files: |
            ./packer-maas/${{ github.event.inputs.image-type }}/*.gz
            ./packer-maas/${{ github.event.inputs.image-type }}/*.gz.part*
