name: test
on:
  push:
  workflow_dispatch:

jobs:
  job1:
    env:
      test: 456
    runs-on: ubuntu-latest
    steps:
      - name: check for secrets needed to run demo
        run: |
          if [ ! -z "${{ secrets.CLOUDTRUTH_API_KEY }}" ]; then
            echo "test=123" >> $GITHUB_ENV
          fi
      - name: test
        if: ${{ env.test=123 }}
        run: echo "test ${{ env.test}}"
