name: test
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "1" > $GITHUB_WORKSPACE/rocky9.tar.gz
      - name: Upload to release file
        uses: softprops/action-gh-release@v2
        with:
          name: v1.0
          tag_name: v1.0
            ./*.gz
